### ISSUE TITLE
项目报名贴（跟帖报名先到先得）7. 二手商品或服务线上竞价交易平台 （5140369044） 

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#10]
二手商品的交易一直在校园内是一个庞大的需求，特别是二手书，标准化程度高。而市场上所提供的服务，一般为规模较大，没有校园细分项的分类信息网，或者是自由度过大，缺少特定竞价或认证功能的论坛式交易平台，用户分散，不能起到良好的信息集中效果。

本平台以二手商品和服务为标的，通过标的标签进行信息分类。普通用户挂牌委托或者提出需求，也可进行浏览和搜索查询需求产品，然后竞价交易。

**Comment by zcwmyself** [comment]
5137409026 报名

**Comment by chenhao1123** [comment]
5140369052

**Comment by 510453684** [comment]
5140369053

**Comment by Evelyn0Nami** [comment]
5140369054

**Comment by wyl1232792** [comment]
po 5140369044

**Comment by zw1003855799** [comment]
5140369049 报名

**Comment by hanxinyuan** [comment]
5140369051

**Comment by mayinghua** [comment]
zcwmyself确认报名后，请关闭本贴。

**Comment by mayinghua** [comment]
zcwmyself，请创建repo，把团队成员和我加入到repo的contributors中去。启动项目。
