### ISSUE TITLE
项目报名贴（跟帖报名先到先得）8.  学习管家  （5140369045）

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#11]
这是款跟学习有关的软件。针对现在学生的需求: 便捷地计算绩点/学积分；获得课程(必修&选修)的简介、教材和过来人的评价；知道学校发生的一些重要新闻以及重要的教务信息；制定自己的学习计划；参与课程讨论。软件内含功能: 绩点/学积分计算器；课程信息；校园新闻；教务小贴士；自定计划表；供某课程学生聊天吐槽的专属聊天室。
（请聚焦功能，做的时候，针对一项功能来做。）

**Comment by xuchao1688** [comment]
po 5140369045

**Comment by Assiduouss** [comment]
BUPO  5140369055

**Comment by mayinghua** [comment]
本项目报名关闭。请xuchao1688和Assiduouss另外报名其他项目。
