### ISSUE TITLE
项目报名贴（跟帖报名先到先得）10.  校内拍卖  （5140369056）

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#13]
校内二手交易有一定需求，然而由于买卖双方之中可能存在对行情不甚了解的人，最终交易价格可能不会让双方满意（尤其是卖方）。拍卖能很好地解决这一问题，然而能提供拍卖的平台不多，京东夺(duo)宝(ming)岛(dao)中多为大件，近距离交易小件不便，而且奖惩措施不力，容易被坑。

**Comment by GeforceGTX** [comment]
po5140369056

**Comment by mayinghua** [comment]
请GeforceGTX到其他项目报名。本项目关闭，不再接受报名了。
