### ISSUE TITLE
项目报名贴（跟帖报名先到先得）11. 滴滴约球  （5140369057）

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#14]
在交大，热衷于运动学生不在少数，其中包括篮球、排球、足球等一系列集体运动方式。但是很多学生苦于没有同伴一起参与运动，或者身边志同道合的同时有时间陪同的同学太少，很难在自己的空闲时间参与这样的集体运动。受到软件滴滴打车的启发，该软件希望为同学们提供一个互动平台，使得大家在希望参加体育运动时能够及时找到相约运动的同伴，实用性强，创新性高，具有很高的发展空间。

**Comment by Quincy2014** [comment]
5140369034

**Comment by fath218** [comment]
5140369038

**Comment by michellehong** [comment]
5140369031

**Comment by scy1243** [comment]
5140369019

**Comment by EXACALIBUR** [comment]
5140369025

**Comment by leafplane** [comment]
5140829015

**Comment by Alex23shi** [comment]
5140369043

**Comment by lynnhe18** [comment]
5137159017

**Comment by mayinghua** [comment]
Quincy2014，如确认报名后，请关闭本帖。

**Comment by ZhangZhuoSJTU** [comment]
我还能报名吗？我是PO……

**Comment by mayinghua** [comment]
quincy2014，给po留位子了么？

**Comment by lynnhe18** [comment]
请问老师我是否还可以留在这组

**Comment by mayinghua** [comment]
顺序报名。建议还是先报其他项目。因为，我需要安排最后几个项目成功组队。

如果后面项目安排不开，有可能加入。

**Comment by mayinghua** [comment]
Quincy2014，请创建repo。添加所有成员（还有我）到repo的contributors中去。项目可以启动了。
