### ISSUE TITLE
项目报名贴（跟帖报名先到先得）12. 同学间借书系统 （5140369058 ）

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#15]
学长学姐必然有些往年的课本无处安放，或者某同学们有些闲置书籍，而这些闲置的资源可以被我们所利用，创造出更大的价值。

**Comment by DGGzhr** [comment]
po5140369058

**Comment by wahaha233** [comment]
5140369039

**Comment by GeforceGTX** [comment]
5140369056

**Comment by Jingyun27** [comment]
712030920068

**Comment by YijenQQ** [comment]
713030920009

**Comment by mayinghua** [comment]
尽管报名尚未结束，本项目可以启动了。wahaha233，作为master，工作可以先做起来了。
1，创建好repo，把现有的团员都加入到repo中去，
2，另外尽快召开第一次会议，让大家好好讨论一下项目的解决方案。

**Comment by Assiduouss** [comment]
5140369055

**Comment by xuchao1688** [comment]
5140369045

**Comment by mayinghua** [comment]
报名结束
