### ISSUE TITLE
项目汇总贴

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#18]
项目名称                      master                              repo link
猫狗校园                     lcdtyph                               https://github.com/lcdtyph/Sweet-Home 
模拟经营类游戏         Irene323                          https://github.com/TPEC/SIM-game 
滴滴约球                 Quincy2014                   https://github.com/Quincy2014/-
手机寻回                   sjtu-lyj                               https://github.com/sjtu-lyj/finding-phone 
二手商品                  zcwmyself                          https://github.com/wyl1232792/SE-Service-Exchange
校园比赛赛事           Buckieyen                    https://github.com/Buckieyen/Campus-competition-event-integral-ranking-system
教师在线                   littledoudou                   https://github.com/littledoudou/Online-dictataion-system
EasyPrint                  LiTianpeng1996             https://github.com/LiTianpeng1996/EasyPrint
同学间借书           wahaha233                       https://github.com/wahaha233/MyBook
校园搭车          Davidsheep                 https://github.com/Davidsheep/Web-Rookies

**Comment by mayinghua** [comment]
完成报名的项目已经关闭，请未报名的同学尽快在open的报名贴中报名。

在关闭的项目中，如果你的报名顺序（除po外）大于6，请继续报名其他项目。

**Comment by mayinghua** [comment]
现在已经有8个项目完成报名。目前仍有4个项目待定。其中只有两个项目会胜出。
按报名数量排序，目前位列第一的是项目5 校园搭车。其他三个项目目前都有2位报名。请同学们集中一下，尽快完成报名并启动项目。

**Comment by mayinghua** [comment]
根据报名情况，目前保留2个项目开放报名。

**Comment by wslxhhh** [comment]
老师，我似乎错过了报名的时间，请问现在还能够参加报名吗？

**Comment by mayinghua** [comment]
yes, you can. there is still one open project left. 


---

**Comment by wslxhhh** [comment]
Thank you！I want to join that project！

**Comment by Davidsheep** [comment]
校园搭车伙伴PO&master   5140369017杨尚喆成员 5140369003金颖5140369004马诗慧5140369023龙军5140369012李鑫5140519017付培玉5140369011戴磊来自我的华为手机-------- 原始邮件 --------主题：Re: [SJTU_SoftwareEngineering] 项目汇总贴 (#18)发件人：Yinghua 收件人：mayinghua/SJTU_SoftwareEngineering 抄送：yes, you can. there is still one open project left. 


---
