### ISSUE TITLE
最后的提醒贴

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#21]
大家好，

两个多月的软工实践就要结束了。这里提醒大家务必12月20日提交大作业。大作业一共分两部分：
一是请项目的master提交项目文档，
二是每一个人都要提交各自的总结文档，将软工中最重要的一个部分：反思，进行到底。

人生就是一场游历，收获总在不经意间。期待大家的总结。

祝好，
马颖华
2015年12月14日

**Comment by sjtu-lyj** [comment]
收到
