### ISSUE TITLE
作业提交情况汇总

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#22]
如发现自己提交，但没有在这个名单里的同学尽快email和我联系。
新收到：
5140369055

提交项目文件包的小组有：
猫狗校园
滴滴约球
校园搭车
经营类游戏
手机寻回
easyprint
二手商品
校园借书
在线默写

已收到的个人总结（仅学号）：
5140369018
5140369024
5140369028
5132029012

5140369006
5140369007
5140369050
5140369015
514079004
5131109035
5140369002

5140519017
5140369017
5140369003
5140369023
5140369004
5140369011
5140369012

5140809011
5140369042
5137159017 
5140369041
5137179022
5140369047

5140369039
5140369056
712030920068
713030920009
5140369045

5140369058

5140369020
5140369022 
5140369046
5140369040
5140369008

5140369049
5140369054
5140369044 
5140369053
5137409026
5140369051
5140369052

5140369034
5140369057
5140369031
5140369025
5140369043
5140829015
5140369038

5140369048
5140369032
5140109055
5140369033
5140369036
5140369030
5140369035

5140369037
5140369001
5140369029
51403669009
5140369027
5140369026
5137119054

5140369013
5140809034
5140369005
5140369014
5140369019
5140369016
 5140729048
5140369021

**Comment by leafplane** [comment]
老师我个人总结你没有收到吗？我学号是5140829015 

发自网易邮箱 iPhone 版
在2015年12月21日 20:22，Yinghua 写道:

如发现自己提交，但没有在这个名单里的同学尽快email和我联系。

提交项目文件包的小组有：
猫狗校园
滴滴约球
校园搭车
经营类游戏
手机寻回
easyprint
二手商品
校园借书
在线默写

已收到的个人总结（仅学号）：
5140369018
5140369024
5140369028
5132029012

5140369006
5140369007
5140369050
5140369015
514079004
5131109035
5140369002

5140519017
5140369017
5140369003
5140369023
5140369004
5140369011
5140369012

5140809011
5140369042
5137159017
5140369041
5137179022
5140369047

5140369039
5140369056
712030920068
713030920009
5140369045

5140369058

5140369020
5140369022
5140369046
5140369040
5140369008

5140369049
5140369054
5140369044
5140369053
5137409026
5140369051
5140369052

5140369034
5140369057
5140369031
5140369025
5140369043
5140829015
5140369038

5140369048
5140369032
5140109055
5140369033
5140369036
5140369030
5140369035

5140369037
5140369001
5140369029
51403669009
5140369027
5140369026
5137119054

5140369013
5140809034
5140369005
5140369014
5140369019
5140369016
5140729048
5140369021

**Comment by mayinghua** [comment]
收到了啊。列表里头有你的学号。你搜一下

----- 原始邮件 -----
发件人: "leafplane" <notifications@github.com>
收件人: "mayinghua/SJTU_SoftwareEngineering" <SJTU_SoftwareEngineering@noreply.github.com>
抄送: "Yinghua" <ma-yinghua@sjtu.edu.cn>
发送时间: 星期二, 2015年 12 月 22日 下午 2:39:35
主题: Re: [SJTU_SoftwareEngineering] 作业提交情况汇总 (#22)


老师我个人总结你没有收到吗？我学号是5140829015 

发自网易邮箱 iPhone 版
在2015年12月21日 20:22，Yinghua 写道:

如发现自己提交，但没有在这个名单里的同学尽快email和我联系。

提交项目文件包的小组有：
猫狗校园
滴滴约球
校园搭车
经营类游戏
手机寻回
easyprint
二手商品
校园借书
在线默写

已收到的个人总结（仅学号）：
5140369018
5140369024
5140369028
5132029012

5140369006
5140369007
5140369050
5140369015
514079004
5131109035
5140369002

5140519017
5140369017
5140369003
5140369023
5140369004
5140369011
5140369012

5140809011
5140369042
5137159017
5140369041
5137179022
5140369047

5140369039
5140369056
712030920068
713030920009
5140369045

5140369058

5140369020
5140369022
5140369046
5140369040
5140369008

5140369049
5140369054
5140369044
5140369053
5137409026
5140369051
5140369052

5140369034
5140369057
5140369031
5140369025
5140369043
5140829015
5140369038

5140369048
5140369032
5140109055
5140369033
5140369036
5140369030
5140369035

5140369037
5140369001
5140369029
51403669009
5140369027
5140369026
5137119054

5140369013
5140809034
5140369005
5140369014
5140369019
5140369016
5140729048
5140369021

—
Reply to this email directly or view it on GitHub.

---
