### ISSUE TITLE
校园助手 报名贴

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#30]

**Comment by dadafafa** [comment]
51530910247（策划）

**Comment by sjtualex** [comment]
515030910093

**Comment by mayinghua** [comment]
0093 同学，你是本组master。你之后5个报名的同学列入项目组。

**Comment by Dongzhenpu** [comment]
515030910420

**Comment by Null-Existence-X** [comment]
515030910634

**Comment by mayinghua** [comment]
@dadafafa 
你应该是这个小组master，上回搞错，请先将repo建起来吧。

**Comment by dadafafa** [comment]
我的联系方式1197369734    ， 没加我的634同学和后面要加入的同学麻烦加一下

**Comment by 394519627hwc** [comment]
515030910416

**Comment by mayinghua** [comment]
有一个460的同学报名，但帖子被隐藏。请@dadafafa注意，这个同学报名在0420同学前面。他可和你直接联系。

**Comment by KevinChensjtu** [comment]
515030910069

**Comment by mayinghua** [comment]
@dadafafa 汇总好名单后，发我email。谢谢

**Comment by leoboy1996** [comment]
515030910249 （其他组不知道自己进没有，通知我换，只剩这一组了，我就缓过来了）
