### ISSUE TITLE
项目报名贴（跟帖报名先到先得）  1   EasyPrint需求分析  (5137119054)

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#4]
在学校里，每到期末考试的时候就会出现这样一种现象——打印店里的人挤得落不下脚，打印店的老板也忙里忙外没有工夫照顾到每一位同学的需要；也有这样一种情形，晚上十点后总是有人在群里询问哪里的打印店还开着，明天一早要交的东西还没有打印，而早上和课间的打印店也是“座无虚席”。但是与此同时，我们可以发现有很多同学在宿舍里自备了打印机，也有的人觉得自备打印机太费钱费墨毕业后还要搬走很麻烦。

所以设计这个软件的目的就是要帮助我们把那些闲下来的打印机充分利用起来，让自备打印机的同学可以收回一点成本，或者通过这种方式交友，也让那些在期末或者深夜无助求打印的人寻找解决的办法。

**Comment by LiTianpeng1996** [comment]
5140369010报名

**Comment by liu601** [comment]
5140369037报名

**Comment by Aimeed10** [comment]
5140369001报名

**Comment by fxnvan** [comment]
5140369009报名

**Comment by zhangrong1117** [comment]
5132029012

**Comment by ier005** [comment]
5140369026报名

**Comment by SadoSun** [comment]
我是PO

**Comment by Wangzheng1997** [comment]
5140369029

**Comment by mayinghua** [comment]
OK，报名已满。LiTianpeng1996请创建repo。

**Comment by xmlmmfev** [comment]
5140369027报名
