### ISSUE TITLE
八个项目课题及组长

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#44]
在50多个题目中优选了10个题目，经过组长认领，选出九个课题，组建项目组。请大家到ftp的“2017软工候选项目”文件夹下查看这9个课题的构思文档。

请大家注意这9个题目的构思者和组长直接入选项目组。请构思者跟帖时，在帖子里明确标明自己的身份。其他同学先到先得（每组严格限制最多7人）。

九个课题如下（9月20日新增一个）：
校园失物招领   肖宇洋
校园信息平台   李昕朋
读书同盟       郑思祺
图书馆预约占座系统   何炳昌
课业难题问答交流 方焯
课程班级管理系统  吕峻
站队投票器	江智昊
校园植物 	严晓峰
学生作业管理软件     刘华玉 （9月20日新增）

周五晚7:00整，会每一个项目开一个新帖，供大家报名。

如果任何问题，可跟帖询问。

**Comment by mayinghua** [comment]
另外，请注意，未在课程报名贴中回帖的同学一定要回帖。如果你的回帖没有显示出来，说明网站把你屏蔽了，怀疑你是机器人。如果是这种情况，需要手工的申诉一下。请大家在项目报名前解决类似问题，否则发帖被屏蔽会导致你报不上名。

**Comment by wangbo-sjtu** [comment]
试一下有没有被屏蔽

**Comment by hebingchang** [comment]
校园信息平台组长应为 李昕朋

**Comment by mayinghua** [comment]
还有5分钟！测试。
