### ISSUE TITLE
516020910229 校园信息平台 项目报名贴

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#47]
项目组组长： 李昕朋

构思者的学号：516020910229 

请用学号跟帖报名

**Comment by Llmoment** [comment]
516030910167

**Comment by shinytang6** [comment]
515020910127

**Comment by lvshengwei** [comment]
516020910229 构思者

**Comment by shinytang6** [comment]
各位，我的联系方式是18221865643，请把我拉进讨论组

**Comment by mayinghua** [comment]
已报名单（组长未列入）： 516030910167 ； 515020910127 ； 516020910220； 516020910229 

暂缺2人

**Comment by nashiluoyuji** [comment]
请加QQ群483915463
