### ISSUE TITLE
项目报名贴（跟帖报名先到先得）  2，猫狗校园  （5140369002）

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#5]
本软件面向交大关爱校园内流浪猫狗的同学，旨在提高交大流浪猫狗的生存质量，关注交大学子们的心理需求。由于现在社会压力大，“踢猫效应”的产生呼吁我们关注社会青年的心理成长和道德树立。同时我校有大量流浪猫狗常驻，同学们与之朝夕相处共同构建和谐校园，而本软件将帮助同学们更好地照顾猫狗们、获得安全的互动关系，也将建立猫狗们对同学们的友好态度，却不致过度依赖。本软件将录入交大常驻猫狗的信息，由同学们提供猫狗性格特征以降低抓伤咬伤事件的发生，有效降低闵行疾病控制中心狂犬病疫苗接种量。

**Comment by wuyutong96** [comment]
5140369007

**Comment by lcdtyph** [comment]
5131109035

**Comment by wuyutong96** [comment]
5140369007

**Comment by gotostudy** [comment]
5140369006

**Comment by asdvh** [comment]
5140369022

**Comment by gtxygdjd** [comment]
5140379004

**Comment by linrx** [comment]
5140369050

**Comment by Serenayin** [comment]
我是po

**Comment by 79cac** [comment]
5140369015

**Comment by mayinghua** [comment]
lcdtyph 请确认报名后，创建repo（最好是公开的），留下repo的链接，并将组员和我都添加进repo的contributors中。

**Comment by lcdtyph** [comment]
https://github.com/lcdtyph/Sweet-Home
怎么添加contributors

**Comment by mayinghua** [comment]
repo页面右侧的settings图标，点进入

**Comment by mashihui** [comment]
5140369004

**Comment by mayinghua** [comment]
mashihui同学这里报名已经结束，你可选择其他项目继续报名。
