### ISSUE TITLE
516030910243 课业难题问答交流app  项目报名贴

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#50]
组长： 方焯
构思者学号： 516030910243 

请用学号跟帖报名

**Comment by huchangyu** [comment]
516030910425胡昶宇

**Comment by fcxlsfy** [comment]
516030910349

**Comment by wangbo-sjtu** [comment]
516030910243 构思者

**Comment by tcqefjm** [comment]
516030910183_冯家铭

**Comment by qjh82353252** [comment]
报名！裘佳浩 516051910022

**Comment by jinzhiyun1998** [comment]
516030910428 金之贇

**Comment by mayinghua** [comment]
最后确认一下名单吧（组长未列入）：
516030910243（构思者） ；516030910425；516030910349；516030910183 ；516051910022 ； 516030910428,。请其他同学另行报名
