### ISSUE TITLE
516030910443 校园植物    项目报名贴

### ISSUE THREAD

**Issue by mayinghua** [mayinghua/SJTU_SoftwareEngineering#53]
组长：  严晓峰

构思者学号： 516030910443

请用学号跟帖报名

**Comment by 516030910307** [comment]
%516030910307郭云浩

**Comment by ChyanMio** [comment]
516030910443张镇睿，项目构思者

**Comment by Amoto1103** [comment]
516030910287 裘炜程

**Comment by themodu** [comment]
516030910137 毛伟俊

**Comment by hhm897510615** [comment]
516030910133 黄浩铭

**Comment by ma-xinghua** [comment]
516030910284

**Comment by mayinghua** [comment]
最后确认一下名单：
516030910283；516030910307；516030910282；516030910443（构思）；516030910137 ；516030910133 。

未在名单中的同学，请另外报名。
